version: 2.1

orbs:
  slack: circleci/slack@4.4.4

commands:
  notify_slack_pass:
    steps:
    - slack/notify:
        event: pass
        template: basic_success_1
  notify_slack_fail:
    steps:
    - slack/notify:
        event: fail
        template: basic_fail_1

jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.6-node-browsers
      environment:
        RAILS_ENV: 'test'
    - image: circleci/mysql:5.7
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        MYSQL_ROOT_HOST: '127.0.0.1'

    working_directory: ~/app

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          gem install bundler
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}
    
    - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-

    - run:
          name: Yarnをinstall
          command: yarn install --cache-folder ~/.cache/yarn

    - run: mv ./config/database.yml.ci ./config/database.yml

    - run:
        name: Databasesetup
        command: |
           bundle exec rake db:create
           bundle exec ridgepole -c config/database.yml -E test --apply -f db/Schemafile
  
    - run: bundle exec bin/webpack

    - run:
        name: Run rspec
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
            circleci tests split --split-by=timings)"

          bundle exec rspec \
            --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/rspec.xml \
            --format progress \
            $TEST_FILES

    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results

    - add_ssh_keys:
        fingerprints:
          - "e8:14:aa:07:ec:76:ab:13:66:63:08:bc:04:ac:80:b3"
    
    - notify_slack_fail
    - notify_slack_pass