default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: myapp_development
  host: localhost
  username: root

test:
  <<: *default
  database: myapp_test
  username: root

production:
  <<: *default
  database: parking_search_production
  username: root
  password: 
  host: localhost
